### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by GioStamoulos** [aromanro/Poisson#4]
I am working on a similar project (a drawing application using MFC and VTK), but I am encountering memory leaks when closing the application (https://discourse.vtk.org/t/memory-leaks-in-vtkrenderwindow-with-parentid/14856) .Have you ever dealt with memory leaks in this application? If so, how did you handle them? 

Your suggestions would be very helpful.

Best regards!

**Comment by aromanro** [comment]
It's been a while since I implemented it... as you could see, I have displaying in a mfc view here, you seem to have it in a child frame. I don't recall issues with memory leaks.

There might be differences between the way I handle initialization and disposal... after a quick glance it seems that I call `Delete()` on the pointers when the view is destroyed, while you don't.

Take a look over the code, maybe it's of some help: https://github.com/aromanro/Poisson/blob/185100523a392fc9096c85b4d422758dad0f7fd4/Poisson/PoissonView.cpp#L66

**Comment by GioStamoulos** [comment]
Thank you for your response. I tried many ways to free memory, but the leaks persisted. If you did not face similar issues, it might indicate that the CMake build of VTK was not configured correctly.

**Comment by aromanro** [comment]
I've just run this app in Debug mode... no leaks were reported.

My suggestion would be to remove all stuff you have in the `~CChildFrame()` destructor and replace it with `->Delete()` calls on all your pointers in the reverse order of their creation.

**Comment by GioStamoulos** [comment]
Your implementation is totally correct. I tried it and also attempted to use smart pointers, which are automatically released. Additionally, I built some MFC examples (~VTK-8.2.0\VTK-8.2.0\Examples\GUI\Win32\SampleMFC) included in the VTK source code (for version 8 and earlier). However, memory leaks also occur in these source example projects.

**Comment by aromanro** [comment]
Be warned that the leaks reported in Debug mode due of 
```
#ifdef _DEBUG
#define new DEBUG_NEW
#endif
```
might not always be real leaks.
